---

root: true

parserOptions:
  ecmaVersion: latest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  import/extensions: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
      - req
      - reply
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
